name: Demo pull with tags

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Pull from Lokalise
        id: lokalise-pull
        uses: bodrovis/Lok-Actions/actions/pull@master
        with:
          api_token: ${{ secrets.LOKALISE_API_TOKEN }}
          project_id: 5007330766e058e0bed4d3.26377346
          translations_path: locales
          file_format: json
          additional_params: "--indentation 2sp --placeholder-format icu"

      - name: Display changed files
        if: steps.lokalise-pull.outputs.pulled_files != ''
        run: |
          echo "Changed files: ${{ steps.lokalise-pull.outputs.pulled_files }}"
